greet = ['CAACAgIAAxkBAAICY2fJsRhXQWoP44t2F5v1YDf7-Qs8AAL_AgACbbBCAwSgOas0AjY3NgQ',
         'CAACAgEAAxkBAAICZ2fJsvxgzvW8tmjReuF58yNnTwkHAAIPAQACOA6CEbXMTX_iFJGCNgQ',
         'CAACAgIAAxkBAAICaWfJsyJ0B1CwMKn4jbY61gI3MmFCAAKaDAAC753ZS6lNRCGaKqt5NgQ',
         'CAACAgEAAxkBAAICa2fJs2h3TxURwQ-00TyCFzDH9jc6AALpAQACOA6CERG4SPQscaSNNgQ']


mouse = 'CAACAgIAAxkBAAICbWfJs8xdk1wNsxEsVxjm9BcIfC24AALyAAP0exkAATs4WmUkIehgNgQ'
cat = 'CAACAgIAAxkBAAICb2fJs96hliOETGMhWPYlsAWIYfGIAALgAAP0exkAASzrKFdeleMwNgQ'
dog = 'CAACAgIAAxkBAAICcWfJs--NE6KUdZ7ReUqKGog6QAVmAAIPAQAC9HsZAAFm9DkUA1TM9DYE'
jag = 'CAACAgIAAxkBAAICc2fJtAfrxoxe4StThTMTwY7YUQABcQACdjkAAoWxyUjGyrP9vvEAAaY2BA'
monk = 'CAACAgIAAxkBAAICdWfJtDKkK9ofYFpdgfUPGAbb_AGRAAL2AAP0exkAAV5hj6W09iesNgQ'
bear = 'CAACAgIAAxkBAAICdWfJtDKkK9ofYFpdgfUPGAbb_AGRAAL2AAP0exkAAV5hj6W09iesNgQ'
seal = 'CAACAgIAAxkBAAICe2fJtHmZOR4WUlTiH3kHQeVuz-DZAAJDAQAC9HsZAAEd5_BFZLHT8jYE'